### ISSUE TITLE
crashes after a while 💩

### ISSUE THREAD

**Issue by ghost** [derhuerst/record-ice-movement#1]
```
(node:23565) UnhandledPromiseRejectionWarning: TypeError: cb is not a function
    at SyncWriteStream.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at SyncWriteStream.destroySoon.SyncWriteStream.destroy (internal/fs/sync_write_stream.js:40:8)
    at /home/pbb/proj/record-ice-movement/node_modules/pump/index.js:45:45
    at call (/home/pbb/proj/record-ice-movement/node_modules/pump/index.js:52:3)
    at Array.forEach (<anonymous>)
    at /home/pbb/proj/record-ice-movement/node_modules/pump/index.js:72:25
    at f (/home/pbb/proj/record-ice-movement/node_modules/once/once.js:25:25)
    at Readable.<anonymous> (/home/pbb/proj/record-ice-movement/node_modules/pump/index.js:31:21)
    at Readable.f (/home/pbb/proj/record-ice-movement/node_modules/once/once.js:25:25)
    at Readable.onerror (/home/pbb/proj/record-ice-movement/node_modules/end-of-stream/index.js:43:12)
(node:23565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by derhuerst** [comment]
Thanks for reporting!

**Comment by derhuerst** [comment]
Probably a bug in [`wifi-on-ice-position-stream`](https://github.com/derhuerst/wifi-on-ice-position-stream), but I don't know where exactly.

**Comment by ghost** [comment]
Until this is fixed I'm using this wonderful script to record the data:

```
#!/bin/bash

trip_json="$(curl https://iceportal.de/api1/rs/tripInfo/trip)"

tripDate="$(echo $trip_json | jq .trip.tripDate -r)"
trainType="$(echo $trip_json | jq .trip.trainType -r)"
vzn="$(echo $trip_json | jq .trip.vzn -r)"
finalStationName="$(echo $trip_json | jq .trip.stopInfo.finalStationName -r)"

name="$(echo ${tripDate}_${trainType}${vzn}_${finalStationName} | sed 's/ /_/g')"

echo "$trip_json" > ${name}_trip.ndjson

while true
do
	echo "$(curl https://iceportal.de/api1/rs/status)" >> ${name}_status.ndjson
	sleep 5
done
```

**Comment by derhuerst** [comment]
I've removed `pump` as of ccf0c83, so this shouldn't appear again.
